# syntax=docker/dockerfile:1.7

# ─── Stage 1 · deps ──────────────────────────────────────────────────────
FROM node:22-alpine AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm ci --no-audit --no-fund --legacy-peer-deps

# ─── Stage 2 · build ─────────────────────────────────────────────────────
FROM node:22-alpine AS builder
WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY . .

# A placeholder is fine at build time — the real key is injected at runtime
# via Cloud Run env vars. The Gemini client lazy-reads it on first request.
ENV NEXT_TELEMETRY_DISABLED=1
ENV GEMINI_API_KEY=build_placeholder

RUN npm run build

# ─── Stage 3 · runtime ───────────────────────────────────────────────────
FROM node:22-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=8080
ENV HOSTNAME=0.0.0.0

# Non-root user
RUN addgroup --system --gid 1001 nodejs \
 && adduser --system --uid 1001 nextjs

# Copy standalone output (server.js + minimal node_modules)
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
COPY --from=builder --chown=nextjs:nodejs /app/public ./public

USER nextjs

EXPOSE 8080

# server.js is generated by Next when output: 'standalone' is set
CMD ["node", "server.js"]
